# Generated by Django 4.2.20 on 2025-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.CharField(max_length=80)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('curriculum', models.TextField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=80, null=True)),
                ('last_update', models.CharField(blank=True, max_length=200, null=True)),
                ('recover_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recover_timestamp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Biografía',
                'verbose_name_plural': 'Biografías',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Órgano',
                'verbose_name_plural': 'Órganos',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name_1', models.CharField(max_length=255)),
                ('last_name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_normalized', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_1_normalized', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_2_normalized', models.CharField(blank=True, max_length=255, null=True)),
                ('first_year', models.SmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10, null=True)),
                ('gemini_link', models.URLField(blank=True, null=True)),
                ('gemini_text', models.TextField(blank=True, null=True)),
                ('academic_ia', models.TextField(blank=True, null=True)),
                ('academic_text', models.TextField(blank=True, null=True)),
                ('professional_ia', models.TextField(blank=True, null=True)),
                ('professional_text', models.TextField(blank=True, null=True)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('more_info_ia', models.TextField(blank=True, null=True)),
                ('more_info_text', models.TextField(blank=True, null=True)),
                ('more_info_summary', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attention_notes_ia', models.TextField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('biography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='oej.biography')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('male_name', models.CharField(blank=True, max_length=255, null=True)),
                ('female_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_body', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_national', models.BooleanField(default=False)),
                ('by_circuit', models.BooleanField(default=False)),
                ('by_circunscription', models.BooleanField(default=False, verbose_name='Por circunscripción')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='oej.body')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('key_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to='oej_icons')),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Poder',
                'verbose_name_plural': 'Poderes',
            },
        ),
        migrations.CreateModel(
            name='StatusControl',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('register', 'Registro'), ('validation', 'Validación'), ('location', 'Ubicación')], default='petition', max_length=10, verbose_name='grupo de status')),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.IntegerField(default=4)),
                ('is_public', models.BooleanField(default=True)),
                ('open_editor', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status de control',
                'verbose_name_plural': 'Status de control (TODOS)',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_mix', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circunscription', models.IntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='oej.position')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='geo.state')),
                ('topics', models.ManyToManyField(related_name='seats', to='oej.topic')),
            ],
            options={
                'verbose_name': 'Escaño',
                'verbose_name_plural': 'Escaños',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_licence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Cédula Profesional')),
                ('career', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesión')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_type', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='Año de expedición')),
                ('other_data', models.JSONField(blank=True, null=True, verbose_name='Datos base')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='oej.candidate')),
            ],
            options={
                'verbose_name': 'Licencia Profesional',
                'verbose_name_plural': 'Licencias Profesionales',
            },
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('circunscription', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_districts', to='geo.state')),
            ],
            options={
                'verbose_name': 'Distrito Electoral Judical',
                'verbose_name_plural': 'Distritos Electorales Judiciales',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='powers',
            field=models.ManyToManyField(related_name='candidates', to='oej.power'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='oej.seat'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_disentir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_disentir', to='oej.statuscontrol'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_laboratorio', to='oej.statuscontrol'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_practica', to='oej.statuscontrol'),
        ),
    ]
