# Generated by Django 4.2.7 on 2025-03-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='full_name_normalized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='find_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionallicense',
            name='is_exact',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
