# Generated by Django 4.2.7 on 2025-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name_normalized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='candidates_photos/'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ElectoralDistrict',
        ),
    ]
