# Generated by Django 4.2.7 on 2025-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0002_biography_full_name_normalized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionallicense',
            old_name='career',
            new_name='title',
        ),
        migrations.AddField(
            model_name='professionallicense',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nivel'),
        ),
    ]
