# Generated by Django 4.2.7 on 2025-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0002_candidate_full_name_normalized_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='price_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
