# Generated by Django 4.2.7 on 2025-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0003_rename_career_professionallicense_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionallicense',
            name='career',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='professionallicense',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título completo'),
        ),
    ]
