# Generated by Django 4.2.7 on 2025-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0003_candidate_price_candidate_price_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='judgments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
