# Generated by Django 4.2.7 on 2025-03-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0004_candidate_judgments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='status_practica',
            new_name='status_register',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='status_laboratorio',
            new_name='status_validation',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='more_info_summary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status_disentir',
        ),
    ]
