# Generated by Django 4.2.7 on 2025-03-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_body_circunscription_power_state_circunscription'),
        ('oej', '0004_professionallicense_career_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
    ]
