# Generated by Django 4.2.7 on 2025-03-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_judicialelectoraldistrict_section'),
        ('oej', '0005_rename_status_practica_candidate_status_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='circunscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='geo.circunscription'),
        ),
    ]
