# Generated by Django 4.2.7 on 2025-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0006_alter_seat_circunscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
