# Generated by Django 4.2.7 on 2025-03-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0007_position_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='color_light',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
