# Generated by Django 4.2.7 on 2025-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0008_position_color_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='total_candidates',
            field=models.IntegerField(default=0, verbose_name='Número de cargos'),
        ),
        migrations.AddField(
            model_name='position',
            name='total_seats',
            field=models.IntegerField(default=0, verbose_name='Número de cargos'),
        ),
    ]
