# Generated by Django 4.2.7 on 2025-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0009_position_total_candidates_position_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='id_ine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ine_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos INE'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo_ine',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la foto del INE'),
        ),
    ]
