# Generated by Django 4.2.7 on 2025-03-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0010_candidate_id_ine_candidate_ine_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
