# Generated by Django 4.2.7 on 2025-04-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0011_candidate_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='photo_ine',
            new_name='ine_photo',
        ),
        migrations.AddField(
            model_name='candidate',
            name='ine_cv',
            field=models.URLField(blank=True, null=True, verbose_name='URL del CV INE'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='num_list',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Número de lista'),
        ),
    ]
