# Generated by Django 4.2.7 on 2025-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0012_rename_photo_ine_candidate_ine_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_small',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='candidates_photos/'),
        ),
    ]
