# Generated by Django 4.2.7 on 2025-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0013_candidate_photo_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='other_sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
