# Generated by Django 4.2.7 on 2025-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0015_candidate_user_register_candidate_user_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ine_cv_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto del CV INE'),
        ),
    ]
