# Generated by Django 4.2.7 on 2025-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0016_candidate_ine_cv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='social_networks',
            field=models.JSONField(blank=True, null=True, verbose_name='Redes sociales'),
        ),
    ]
