# Generated by Django 4.2.7 on 2025-04-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0017_candidate_social_networks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('keywords', models.JSONField(blank=True, help_text='Palabras claves para la búsqueda', null=True)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='social_networks',
            new_name='accounts',
        ),
        migrations.CreateModel(
            name='SocialNetworkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('page_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la página')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='oej.candidate')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='oej.socialnetwork')),
            ],
        ),
    ]
