# Generated by Django 4.2.7 on 2025-04-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_topic_and_more'),
        ('oej', '0018_socialnetwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='topics',
        ),
        migrations.AddField(
            model_name='position',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='candidates_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos de candidatos'),
        ),
        migrations.AddField(
            model_name='seat',
            name='final_positions',
            field=models.IntegerField(default=0, verbose_name='Número de cargos finales'),
        ),
        migrations.AddField(
            model_name='seat',
            name='judicial_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='geo.judicialelectoraldistrict'),
        ),
        migrations.AddField(
            model_name='seat',
            name='probability_hombres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Probabilidad de hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='probability_mujeres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Probabilidad de mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='real_hombres',
            field=models.IntegerField(default=0, verbose_name='Número de hombres compitiendo'),
        ),
        migrations.AddField(
            model_name='seat',
            name='real_mujeres',
            field=models.IntegerField(default=0, verbose_name='Número de mujeres compitiendo'),
        ),
        migrations.AddField(
            model_name='seat',
            name='shared_positions',
            field=models.IntegerField(default=0, verbose_name='Más cargos que espacios'),
        ),
        migrations.AddField(
            model_name='seat',
            name='shared_squares',
            field=models.IntegerField(default=0, verbose_name='Más espacios que cargos'),
        ),
        migrations.AddField(
            model_name='seat',
            name='squares_hombres',
            field=models.IntegerField(default=0, verbose_name='Número de espacios para hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='squares_mujeres',
            field=models.IntegerField(default=0, verbose_name='Número de espacios para mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='geo.topic'),
        ),
        migrations.AddField(
            model_name='seat',
            name='topic_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Índice de materia'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
