# Generated by Django 4.2.7 on 2025-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0019_remove_seat_topics_position_acronym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='shared_positions',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='shared_squares',
        ),
        migrations.AddField(
            model_name='seat',
            name='plus_squares',
            field=models.IntegerField(default=0, verbose_name='Espacios de más (+) o de menos (-)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_positions',
            field=models.IntegerField(default=0, verbose_name='Número de cargos disponibles'),
        ),
    ]
