# Generated by Django 4.2.7 on 2025-05-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_anomaly'),
        ('oej', '0020_remove_seat_shared_positions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='final_positions',
            new_name='total_offices',
        ),
        migrations.AddField(
            model_name='candidate',
            name='anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='geo.anomaly'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Probabilidad de ser candidato'),
        ),
        migrations.AddField(
            model_name='seat',
            name='offices_hombres',
            field=models.IntegerField(default=0, verbose_name='Número de cargos asignados a hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='offices_mujeres',
            field=models.IntegerField(default=0, verbose_name='Número de cargos asignados a mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='selected_hombres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hombres elegidos'),
        ),
        migrations.AddField(
            model_name='seat',
            name='selected_mujeres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mujeres elegidas'),
        ),
        migrations.AddField(
            model_name='seat',
            name='shared_offices',
            field=models.IntegerField(default=0, verbose_name='Número de cargos compartidos'),
        ),
    ]
