# Generated by Django 4.2.7 on 2025-05-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_anomaly'),
        ('oej', '0021_rename_final_positions_seat_total_offices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_candidates', to='geo.anomaly'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='final_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidad final de ser candidato'),
        ),
        migrations.AddField(
            model_name='seat',
            name='final_selected_hombres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hombres elegidos (final)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='final_selected_mujeres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mujeres elegidas (final)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='gender_forced',
            field=models.BooleanField(default=False, verbose_name='Por paridad, debe ser mujer'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidad de ser candidato'),
        ),
    ]
