# Generated by Django 4.2.7 on 2025-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0022_candidate_final_anomaly_candidate_final_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='final_selected_hombres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hombres elegidos (final)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_selected_mujeres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mujeres elegidas (final)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='gender_forced',
            field=models.IntegerField(default=0, verbose_name='Por paridad, debe ser mujer'),
        ),
    ]
