# Generated by Django 4.2.7 on 2025-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0023_alter_seat_final_selected_hombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='final_probability_hombres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidad final de hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='final_probability_mujeres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidad final de mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='men_forced_probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prob. de que por paridad los hombres no sean elegidos'),
        ),
        migrations.AddField(
            model_name='seat',
            name='women_forced_probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prob. de que por paridad las mujeres sean elegidas'),
        ),
    ]
