# Generated by Django 4.2.7 on 2025-05-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0024_seat_final_probability_hombres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='men_forced_probability',
            new_name='forced_probability_hombres',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='women_forced_probability',
            new_name='forced_probability_mujeres',
        ),
    ]
