# Generated by Django 4.2.7 on 2025-05-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0025_rename_men_forced_probability_seat_forced_probability_hombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Última probabilidad de ser candidato'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='simulations',
            field=models.JSONField(blank=True, null=True, verbose_name='Simulaciones'),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_simulations',
            field=models.BooleanField(default=False, verbose_name='Simulaciones realizadas'),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_probability_hombres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Última probabilidad de hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_probability_mujeres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Última probabilidad de mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_selected_hombres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hombres elegidos (último)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_selected_mujeres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mujeres elegidas (último)'),
        ),
    ]
