# Generated by Django 4.2.7 on 2025-05-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0026_candidate_last_probability_candidate_simulations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='last_probability',
            new_name='circuit_probability',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='last_probability_hombres',
            new_name='circuit_probability_hombres',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='last_probability_mujeres',
            new_name='circuit_probability_mujeres',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='last_selected_hombres',
            new_name='circuit_selected_hombres',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='last_selected_mujeres',
            new_name='circuit_selected_mujeres',
        ),
    ]
