# Generated by Django 4.2.7 on 2025-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0027_rename_last_probability_candidate_circuit_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='winners',
            field=models.JSONField(blank=True, null=True, verbose_name='Ganadores'),
        ),
        migrations.AddField(
            model_name='seat',
            name='circuit_forced_probability_hombres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prob. de que por paridad los hombres no sean elegidos'),
        ),
        migrations.AddField(
            model_name='seat',
            name='circuit_forced_probability_mujeres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prob. de que por paridad las mujeres sean elegidas'),
        ),
    ]
