# Generated by Django 4.2.7 on 2025-05-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_anomaly'),
        ('oej', '0028_candidate_winners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='circuit_anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_candidates', to='geo.anomaly'),
        ),
    ]
