# Generated by Django 4.2.7 on 2025-05-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0029_candidate_circuit_anomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='circuit_probability',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Última probabilidad de ser candidato'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='final_probability',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Probabilidad final de ser candidato'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Probabilidad de ser candidato'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_forced_probability_hombres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Prob. de que por paridad los hombres no sean elegidos'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_forced_probability_mujeres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Prob. de que por paridad las mujeres sean elegidas'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_probability_hombres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Última probabilidad de hombres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_probability_mujeres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Última probabilidad de mujeres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_selected_hombres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Hombres elegidos (último)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='circuit_selected_mujeres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Mujeres elegidas (último)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_probability_hombres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Probabilidad final de hombres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_probability_mujeres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Probabilidad final de mujeres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_selected_hombres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Hombres elegidos (final)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='final_selected_mujeres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Mujeres elegidas (final)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='forced_probability_hombres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Prob. de que por paridad los hombres no sean elegidos'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='forced_probability_mujeres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Prob. de que por paridad las mujeres sean elegidas'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='probability_hombres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Probabilidad de hombres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='probability_mujeres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Probabilidad de mujeres'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='selected_hombres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Hombres elegidos'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='selected_mujeres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Mujeres elegidas'),
        ),
        migrations.CreateModel(
            name='SimulationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_params', models.JSONField(blank=True, null=True)),
                ('simulation_text', models.TextField(blank=True, null=True)),
                ('simulation_ia', models.TextField(blank=True, null=True)),
                ('simulation_summary', models.TextField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_seats', to='oej.seat')),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
            },
        ),
    ]
