# Generated by Django 4.2.7 on 2025-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0030_alter_candidate_circuit_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Votos finales'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='real_winner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ganador real (init)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='real_winner_circuit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ganador real (último)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='real_winner_final',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ganador real (1ra)'),
        ),
    ]
