# Generated by Django 4.2.7 on 2025-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0031_candidate_final_votes_candidate_real_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='nominal_list',
            field=models.IntegerField(default=0, verbose_name='Número de personas en la lista nominal'),
        ),
        migrations.AddField(
            model_name='seat',
            name='null_votes_hombres',
            field=models.IntegerField(default=0, verbose_name='Votos nulos de hombres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='null_votes_mujeres',
            field=models.IntegerField(default=0, verbose_name='Votos nulos de mujeres'),
        ),
        migrations.AddField(
            model_name='seat',
            name='voted_people',
            field=models.IntegerField(default=0, verbose_name='Número de personas que votaron'),
        ),
    ]
