# Generated by Django 4.2.7 on 2025-06-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oej', '0032_seat_nominal_list_seat_null_votes_hombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='spend_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gasto mínimo estimado'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='spend_upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gasto máximo estimado'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_ads',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número total de anuncios'),
        ),
    ]
