# Generated by Django 4.2.20 on 2025-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion
import gossip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GossipResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source_link', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=30, null=True)),
                ('valid_filled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Respuesta al Formulario',
                'verbose_name_plural': 'Respuestas al Formulario',
            },
        ),
        migrations.CreateModel(
            name='ResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=gossip.models.upload_to_gossip_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gossip_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gossip.gossipresponse')),
            ],
            options={
                'verbose_name': 'Archivo de Respuesta',
                'verbose_name_plural': 'Archivos de Respuesta',
            },
        ),
    ]
