# Generated by Django 4.2.7 on 2025-03-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Órgano',
                'verbose_name_plural': 'Órganos',
                'db_table': 'oej_body',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('key_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to='oej_icons')),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Poder',
                'verbose_name_plural': 'Poderes',
                'db_table': 'oej_power',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=2, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Corto')),
                ('code_name', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nombre Clave')),
                ('circuit', models.IntegerField(blank=True, null=True, verbose_name='Circuito electoral')),
                ('alternative_names', models.JSONField(default=list, help_text='Ocupar para OCAMIS', verbose_name='Lista nombres alternativos')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'borde_state',
                'ordering': ['inegi_code'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('complete_code', models.CharField(max_length=8, verbose_name='Clave INEGI Completa')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('std_name', models.CharField(max_length=255, verbose_name='Nombre Estandarizado')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud de cabecera')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud de cabecera')),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='Altitud de cabecera')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='geo.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['inegi_code'],
            },
        ),
    ]
