# Generated by Django 4.2.7 on 2025-03-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Circunscripción',
                'verbose_name_plural': 'Circunscripciones',
                'db_table': 'oej_circunscription',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='circunscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geo.circunscription'),
        ),
    ]
