# Generated by Django 4.2.7 on 2025-03-30 19:31

from django.db import migrations, models
import django.db.models.deletion


def load_Circunscriptions(apps, schema_editor):
    Circunscription = apps.get_model('geo', 'Circunscription')
    for circ in range(1, 6):
        Circunscription.objects.create(
            name=f'Circunscripción {circ}',
            number=circ,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_circunscription_state_circunscription'),
    ]

    operations = [
        migrations.RunPython(load_Circunscriptions),
        migrations.CreateModel(
            name='JudicialElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('federal_district', models.IntegerField(blank=True, null=True, verbose_name='Distrito electoral')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_electoral_districts', to='geo.state')),
            ],
            options={
                'verbose_name': 'Distrito Electoral Judicial',
                'verbose_name_plural': 'Distritos Electorales Judiciales',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('federal_district', models.IntegerField(blank=True, null=True, verbose_name='Distrito electoral')),
                ('judicial_electoral_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='geo.judicialelectoraldistrict')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
