# Generated by Django 4.2.7 on 2025-03-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_judicialelectoraldistrict_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='icon_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='oej_icons'),
        ),
        migrations.AlterField(
            model_name='power',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
