# Generated by Django 4.2.7 on 2025-04-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_power_icon_image_alter_power_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.RemoveField(
            model_name='judicialelectoraldistrict',
            name='federal_district',
        ),
        migrations.AddField(
            model_name='judicialelectoraldistrict',
            name='second_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judicial_electoral_districts_2', to='geo.state'),
        ),
    ]
