# Generated by Django 4.2.7 on 2025-04-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judicialelectoraldistrict',
            name='circuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Circuito electoral'),
        ),
        migrations.AlterField(
            model_name='judicialelectoraldistrict',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judicial_electoral_districts', to='geo.state'),
        ),
        migrations.AlterUniqueTogether(
            name='judicialelectoraldistrict',
            unique_together={('circuit', 'number')},
        ),
        migrations.RemoveField(
            model_name='judicialelectoraldistrict',
            name='name',
        ),
    ]
