# Generated by Django 4.2.7 on 2025-05-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_judicialelectoraldistrict_circuit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('key_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
            },
        ),
    ]
