# Generated by Django 4.2.7 on 2025-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, help_text='Color del usuario', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, help_text='Iniciales del usuario', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Organización del usuario', max_length=100, null=True),
        ),
    ]
